//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectedItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectedItem()
        {
            this.Distributions = new HashSet<Distribution>();
        }
    
        public int Id { get; set; }
        public int ReqId { get; set; }
        public string FoodName { get; set; }
        public string Quantity { get; set; }
        public int EmployeeId { get; set; }
        public System.TimeSpan StoreTime { get; set; }
        public System.TimeSpan ExpireTime { get; set; }
    
        public virtual CollectionRequest CollectionRequest { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Distribution> Distributions { get; set; }
    }
}
