//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectionRequest()
        {
            this.CollectedItems = new HashSet<CollectedItem>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string FoodName { get; set; }
        public string Quantity { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan MaxPreservationTime { get; set; }
        public Nullable<System.TimeSpan> CollectTime { get; set; }
        public Nullable<int> employeeId { get; set; }
        public int userid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectedItem> CollectedItems { get; set; }
        public virtual RegisteredRestaurant RegisteredRestaurant { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
