//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int Id { get; set; }
        public int CollectionId { get; set; }
        public string DistributedLocation { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan DistributedTime { get; set; }
        public string FoodName { get; set; }
        public string Quantity { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual CollectedItem CollectedItem { get; set; }
        public virtual User User { get; set; }
    }
}
